services:      

  mysqldb:
    image: mysql/mysql-server:5.7
    container_name: mysqldb
    restart: always
    environment:
      #MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: savvis2_write      
      #MYSQL_PASSWORD: root
      #MYSQL_USER: root
    ports:
      - 3316:3306
    #expose:
      #- 3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/createSchema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/createTableEmployee.sql:/docker-entrypoint-initdb.d/2.sql
      - ./scripts/createTableSchool.sql:/docker-entrypoint-initdb.d/3.sql
    networks:   
      - mysql-net
      
  multi_schema_service:
    container_name: multidbserver    
    build:
      context:  .
      dockerfile: Dockerfile
    restart: always  
    ports:
      - 8081:8081     

    depends_on:
      - mysqldb     
    networks:
      - mysql-net
    healthcheck:
      test: [ "CMD", "root", "ping", "-h", "mysqldb", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      
volumes:
  mysql_data:
    driver: local
networks:
  mysql-net:
    driver: bridge
